### ISSUE TITLE
is there any methed make POOL.execute rerute dict?

### ISSUE THREAD

**Issue by aq2004723** [PyMySQL/Tornado-MySQL#10]
HI:

Now, I want to write a RESTFUL API with tornado and i want to know is there any methed make POOL.execute rerute dict?

thanks

**Comment by methane** [comment]
Pool has `connect_kwargs` option: https://github.com/PyMySQL/Tornado-MySQL/blob/master/tornado_mysql/pools.py#L33
You can pass `cursorclass=DictCursor` to connection via it.
