### ISSUE TITLE
Hi,I try pool demo,it doesn't run.

### ISSUE THREAD

**Issue by woshihaoren** [PyMySQL/Tornado-MySQL#13]
centos7.1
python2.7.5

it‘s block,and doesn't run print(n, cur.fetchall()).

[root@localhost Ease]# python t1.py 
0 sleeping 1 seconds
1 sleeping 1 seconds
2 sleeping 1 seconds
3 sleeping 1 seconds
4 sleeping 1 seconds
5 sleeping 1 seconds
6 sleeping 1 seconds
7 sleeping 1 seconds
8 sleeping 1 seconds
9 sleeping 1 seconds

**Comment by wikimore** [comment]
hi,woshihaoren:
   this maybe a bug, because the default max_open_connections is 0,  you can set the value of max_open_connections to any value bigger than 0，then it will work.

**Comment by woshihaoren** [comment]
Yeah, you are right. it's OK

**Comment by shuax** [comment]
I also have the same problem.This example is too strange.

**Comment by methane** [comment]
This is not a problem of example.
See #7.
