### ISSUE TITLE
Release a new version to fix the pool hungup bug 

### ISSUE THREAD

**Issue by ldsink** [PyMySQL/Tornado-MySQL#18]
Hi,
I use PyPi upgrade Tornado-MySQL to latest stable version（0.5） and I find all connection pool don't work. 
If a pool don't set `max_open_connections` option, the pool won't create new connection and cause program hangup.
This bug already fixed in master branch by [this commit](https://github.com/PyMySQL/Tornado-MySQL/commit/4951ec25a49bec5d25ead95b162b4b61fd092020), but it don't release a new version after that.
I hope you can release a new version to PyPi as soon as possible.

**Comment by methane** [comment]
0.5.1 has been released.
