### ISSUE TITLE
how to set read_timeout?

### ISSUE THREAD

**Issue by tangzhenquan** [PyMySQL/Tornado-MySQL#19]
how to set read_timeout?

**Comment by methane** [comment]
There isn't way to set it.

I recommend to use threadpool and blocking MySQL driver (e.g. MySQL Connector/Python or mysqlclient-python).
It's more robust, efficient and fast.

**Comment by tangzhenquan** [comment]
In theory, Threadpool and blocking MySQL driver  may be more inefficient and slow,

**Comment by methane** [comment]
Have you read this blog post?
http://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/
