### ISSUE TITLE
can't get a connection when using connection pool if max_open_connections=0 

### ISSUE THREAD

**Issue by newdefence** [PyMySQL/Tornado-MySQL#26]
File: tornado_mysql/pools.py
`

    class Pool(object):

        def _get_conn(self):
`
my code:
mypool = tornado_mysql.pool.Pool(**{host:"localhost"})

then self._free_conn if empty forever, equal to false
self.max_open = 0, equal to false

now, the pool is waiting for a connection, but there is no chance to create a connection.

![tornado_mysql_pools](https://cloud.githubusercontent.com/assets/1746103/12772733/175eb126-ca6f-11e5-8b0e-6bdadd9bdbeb.png)

thanks to fix the bug.

**Comment by methane** [comment]
Which version did you use???
See 4951ec25
