### ISSUE TITLE
what is the problem?

### ISSUE THREAD

**Issue by fkdtz** [PyMySQL/Tornado-MySQL#34]
> This library is experimental. Don't use for production unless you can fix problem yourself.

I like Tornado-MySQL very much. it is useful.
I am concerned about the problem.
what is the problem?
which condition can cause the problem?

**Comment by methane** [comment]
This sentence means "I'm not free tech support for you.  I won't investigate your problem.".

I've very tired about issue report like "this doesn't works for me" with only few lines of (unexecutable) code.  Writing English is hard job to me.  I don't want to ask questions like "What is your OS? What is your MySQL version? Could you give me reproducible complete code? What shown when adding this log?, etc etc..."

> what is the problem?

* What you encounter.
* Generic problem about networking programming with Tornado.
* Issue fixed on upstream PyMySQL, but not ported to this projects.  I won't pay my time to listing them.  You can see PyMySQL commit log if you interested in.

> which condition can cause the problem?

Vary.  Misconfigured MySQL, misconfigured OS, ulimit, blocking file I/O, CPU bound job, etc etc...

**Comment by fkdtz** [comment]
Thank you very much!
