### ISSUE TITLE
Random Response corruption

### ISSUE THREAD

**Issue by bspacedevops** [PyMySQL/Tornado-MySQL#37]
Hi, I have been using tornado with tornado-mysql. And we run this stack in high throughput servers on AWS (EC2 and RDS). Till a week back everything was running smoothly, but recently we have been getting the the following errors from our code. The diagnosis suggests that the Tornado-MYSQL driver has been responding with **empty "tuple"'s**, that too quite **erratically**.

``` python
Traceback (most recent call last):
  File "/home/ec2-user/server/core-api/app-server.py", line 606, in get
    auth = await check_auth(pool=pool, token=token, session_size=config.session_size)
  File "/home/ec2-user/server/core-api/core/users/auth.py", line 45, in check_auth
    if (timenow - ts) < session_size * 3600):
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

and

``` python
Traceback (most recent call last):
  File "/home/ec2-user/server/core-api/app-server.py", line 606, in get
    auth = await check_auth(pool=pool, token=token, session_size=config.session_size)
  File "/home/ec2-user/server/core-api/core/users/auth.py", line 39, in check_auth
    ts = check[5]
IndexError: tuple index out of range
```

The query for both the exception is as follows:

``` sql
SELECT u_id, chain_id, rest_id, designation, BIN(permission), ts 
FROM user.auth 
WHERE o_tk = %s;
```

What could be the issue and how do I solve it?
Any help is appreciated as tornado-mysql is a crucial part of our stack.

**Comment by methane** [comment]
> What could be the issue

Multiple threads use same pool, or multiple coroutine use same connection concurentlly, timeout happen during waiting result, etc...

> how do I solve it?

Review your code carefully, and check one connection is not used from multi coroutine concurrently,
don't reuse connection without reading full result (this happens when timeout especially).

**Comment by bspacedevops** [comment]
Thanks for the reply methane. 

I have been reviewing the code, and I haven't been able to find any code where a connection is being used concurrently by multiple co-routines concurrently.(as per my knowledge :)).

The general way by which we communicate with the database is 

cur = pool.execute(query, [arguments])  
OR
cur = txn.execute(query, [arguments]), where txn denotes a Transaction object

followed by cur.fetchone() or a cur.fetchall().

Could you please provide me with a few code examples where-in connections are used concurrently, not sure if driver has functions to do this?

Since our database has grown is size, could this be because cur.fetchall() is failing because of memory pressure.

Also, 
all connections to the database are in a try and exception block with adequate logging, so shouldn't timeout be raising an operational error, which would then get printed? Unfortunately not seeing any logs regarding the same, and hence am confused.

**Comment by methane** [comment]
I don't have energy and time for this project.
I recommend you to use aiomysql instead of this.

Tornado can use asyncio libraries now.
So this project is only for dying language: Python 2.
