### ISSUE TITLE
multiple queries with warnings in one execute()

### ISSUE THREAD

**Issue by kyle-lu** [PyMySQL/Tornado-MySQL#39]
```
sql = "DROP PROCEDURE IF EXISTS test; CREATE PROCEDURE test() SELECT 1"
yield db.execute(sql)
```
The `DROP` would cause a warning if procedure not existed, but `CREATE` would succeed. `result.warning_count` would not be 0, but `conn.show_warnings()` would be empty. 
Resulting uncaught exception.

**Comment by methane** [comment]
won't fix.  Go Python3 & asyncio.
