### ISSUE TITLE
Stream is closed

### ISSUE THREAD

**Issue by mx472756841** [PyMySQL/Tornado-MySQL#44]
Hi, I encountered a problem when using the connection **_pool_**.

I see the source code

```python
    def _get_conn(self):
        now = self.io_loop.time()

        # Try to reuse in free pool
        while self._free_conn:
            conn = self._free_conn.popleft()
            if now - conn.connected_time > self.max_recycle_sec:
                self._close_async(conn)
                continue
            log.debug("Reusing connection from pool: %s", self.stat())
            fut = Future()
            fut.set_result(conn)
            return fut
    ......
```
```python
conn = self._free_conn.popleft()
if now - conn.connected_time > self.max_recycle_sec:
    self._close_async(conn)
    continue
```
If conn is closed at this time, 
but  now - conn.connected_time <= self.max_recycle_sec,
Using conn at this point will throw **_tornado.iostream.StreamClosedError: Stream is closed_**
But I can't find where this **_conn_** was closed.

**Comment by methane** [comment]
Surely, you need to find it in your application.
Why do you bother me?

**Comment by mx472756841** [comment]
I'm very sorry to bother you, man.

I just want to find the problem

**Comment by methane** [comment]
Have you read README?
If you don't have expert colleague who can investigate it, I recommend you to stop using this library.

**Comment by mx472756841** [comment]
Thanks, I will consider
